name: Upload Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Write PyPI credentials to ~/.pypirc
      run: |
        echo "[pypi]" >> $HOME/.pypirc
        echo "username = __token__" >> $HOME/.pypirc
        echo "password = ${{ secrets.PYPI_TOKEN }}" >> $HOME/.pypirc
        
    - name: Install dependencies and final upload
      run: |
        python -m pip install -r requirements.txt
        pip install twine
        python setup.py sdist
        twine upload dist/*
